const data = [
  {
    _id: '5e43e2877db3b023f00fbaa8',
    index: 0,
    guid: 'b2464be5-3040-42be-b234-8287bbdb4e65',
    isActive: true,
    balance: '$1,092.18',
    picture: 'http://placehold.it/32x32',
    age: 38,
    eyeColor: 'brown',
    name: 'Marion Levine',
    gender: 'female',
    company: 'TERAPRENE',
    email: 'marionlevine@teraprene.com',
    phone: '+1 (967) 562-3893',
    address: '322 Ide Court, Brookfield, Oklahoma, 6584',
    about: 'Ad proident do sit pariatur ad aliqua ut eu reprehenderit. Officia aute proident laborum ipsum fugiat irure mollit voluptate occaecat fugiat id exercitation officia. Enim est non eu laborum id magna deserunt ea cupidatat aute nisi dolor ad esse. Incididunt consectetur sint quis veniam pariatur tempor proident. Sint irure quis non sint cupidatat. Anim sint eu culpa fugiat nisi dolore. Sunt cillum cillum consequat culpa duis nostrud enim ea.\r\n',
    registered: '2019-01-03T07:43:17 -03:00',
    latitude: 56.474454,
    longitude: 94.013175,
    tags: [
      'exercitation',
      'reprehenderit',
      'cillum',
      'ad',
      'minim',
      'eu',
      'labore',
    ],
    friends: [
      {
        id: 0,
        name: 'Valeria Hicks',
      },
      {
        id: 1,
        name: 'Pena West',
      },
      {
        id: 2,
        name: 'Lucia Flynn',
      },
    ],
    greeting: 'Hello, Marion Levine! You have 4 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '5e43e28737e6556ae641fd96',
    index: 1,
    guid: '4f67f1ce-010b-4569-8cc7-78a4873222f6',
    isActive: true,
    balance: '$2,456.13',
    picture: 'http://placehold.it/32x32',
    age: 26,
    eyeColor: 'green',
    name: 'Weber Johnston',
    gender: 'male',
    company: 'MAROPTIC',
    email: 'weberjohnston@maroptic.com',
    phone: '+1 (982) 555-3126',
    address: '704 Orient Avenue, Stonybrook, Washington, 3642',
    about: 'Ex esse cillum commodo qui commodo ullamco laboris. Do officia culpa adipisicing ex eiusmod occaecat minim sunt aliquip enim cupidatat quis dolor. In ut enim ad amet ea culpa irure enim anim excepteur voluptate enim.\r\n',
    registered: '2019-09-28T09:49:37 -03:00',
    latitude: 89.47084,
    longitude: 171.514262,
    tags: [
      'mollit',
      'laborum',
      'tempor',
      'eu',
      'velit',
      'sint',
      'est',
    ],
    friends: [
      {
        id: 0,
        name: 'Josefa Rutledge',
      },
      {
        id: 1,
        name: 'Kathy Yates',
      },
      {
        id: 2,
        name: 'Rowena Justice',
      },
    ],
    greeting: 'Hello, Weber Johnston! You have 5 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '5e43e287e584c2829f93afb1',
    index: 2,
    guid: '16cb98c8-aca6-413b-833a-35b63f922dcc',
    isActive: true,
    balance: '$2,071.15',
    picture: 'http://placehold.it/32x32',
    age: 35,
    eyeColor: 'green',
    name: 'Greer Hudson',
    gender: 'male',
    company: 'ZYTREK',
    email: 'greerhudson@zytrek.com',
    phone: '+1 (994) 540-3371',
    address: '608 Knapp Street, Beechmont, South Dakota, 4576',
    about: 'Proident amet irure enim ipsum duis esse mollit magna deserunt. Quis consequat amet nostrud consectetur eiusmod ea velit irure proident anim ea aliqua est. Eu deserunt sint consectetur officia. Pariatur minim cupidatat excepteur voluptate sunt ut dolor duis. Ex mollit et aliquip ad ut tempor ullamco. Reprehenderit anim esse proident et consectetur ut.\r\n',
    registered: '2015-05-21T11:55:25 -03:00',
    latitude: 10.688608,
    longitude: -97.168986,
    tags: [
      'adipisicing',
      'elit',
      'elit',
      'cillum',
      'reprehenderit',
      'elit',
      'non',
    ],
    friends: [
      {
        id: 0,
        name: 'Hammond Mills',
      },
      {
        id: 1,
        name: 'Annabelle Morris',
      },
      {
        id: 2,
        name: 'Gladys Hyde',
      },
    ],
    greeting: 'Hello, Greer Hudson! You have 4 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '5e43e287d976668427481203',
    index: 3,
    guid: '14a4133f-1c3e-4467-82e8-bb6e31012364',
    isActive: true,
    balance: '$1,619.53',
    picture: 'http://placehold.it/32x32',
    age: 23,
    eyeColor: 'green',
    name: 'Kline Gomez',
    gender: 'male',
    company: 'ANARCO',
    email: 'klinegomez@anarco.com',
    phone: '+1 (936) 532-3013',
    address: '358 Verona Street, Ryderwood, Marshall Islands, 2786',
    about: 'Excepteur duis non dolor ut aliqua eu pariatur ipsum magna. Commodo pariatur veniam occaecat anim consectetur do sit id quis voluptate et non. Aliquip Lorem et fugiat incididunt exercitation incididunt cupidatat cillum id eu veniam nulla est anim. Aliquip ad laborum cillum elit officia esse officia id duis occaecat est fugiat. Do cillum eu cillum duis. Proident ut pariatur amet nostrud sunt nulla et ullamco excepteur velit dolor id ullamco esse. Ad dolore do laborum fugiat consectetur tempor deserunt velit labore anim magna.\r\n',
    registered: '2019-05-18T09:50:45 -03:00',
    latitude: 72.843058,
    longitude: -39.398198,
    tags: [
      'irure',
      'magna',
      'fugiat',
      'laborum',
      'eu',
      'labore',
      'cillum',
    ],
    friends: [
      {
        id: 0,
        name: 'Haley Key',
      },
      {
        id: 1,
        name: 'Luisa Burch',
      },
      {
        id: 2,
        name: 'Haley Wolfe',
      },
    ],
    greeting: 'Hello, Kline Gomez! You have 2 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '5e43e287651498b4180aaadd',
    index: 4,
    guid: '608c9818-2599-42dc-a26b-26040ba00fa8',
    isActive: false,
    balance: '$1,066.60',
    picture: 'http://placehold.it/32x32',
    age: 33,
    eyeColor: 'blue',
    name: 'Hester Craft',
    gender: 'female',
    company: 'QABOOS',
    email: 'hestercraft@qaboos.com',
    phone: '+1 (952) 440-2758',
    address: '360 Juliana Place, Cleary, Wyoming, 3518',
    about: 'Commodo nulla Lorem do non exercitation. Occaecat culpa dolor mollit minim amet commodo. Dolor incididunt duis elit exercitation enim. Exercitation adipisicing laborum id fugiat pariatur est labore culpa ad labore. Deserunt occaecat Lorem amet sit minim non amet.\r\n',
    registered: '2018-09-09T07:37:49 -03:00',
    latitude: -56.383618,
    longitude: -25.107901,
    tags: [
      'incididunt',
      'cillum',
      'tempor',
      'Lorem',
      'qui',
      'eiusmod',
      'laborum',
    ],
    friends: [
      {
        id: 0,
        name: 'Byrd Moreno',
      },
      {
        id: 1,
        name: 'Mann George',
      },
      {
        id: 2,
        name: 'Riley Rodgers',
      },
    ],
    greeting: 'Hello, Hester Craft! You have 7 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '5e43e287352d21d219cbb218',
    index: 5,
    guid: '4aa399bf-98cc-498b-b0b1-90fb523576d6',
    isActive: false,
    balance: '$2,824.64',
    picture: 'http://placehold.it/32x32',
    age: 33,
    eyeColor: 'green',
    name: 'Slater Marsh',
    gender: 'male',
    company: 'RECRITUBE',
    email: 'slatermarsh@recritube.com',
    phone: '+1 (956) 578-3038',
    address: '583 Lee Avenue, Richville, Rhode Island, 2845',
    about: 'Eu aute proident voluptate sunt duis. Commodo ipsum non Lorem veniam sit culpa quis do officia sint amet enim sunt. Velit duis voluptate incididunt proident laborum anim quis commodo. Fugiat tempor aliquip ad ad proident reprehenderit do laborum. Duis anim ut officia sunt eu enim nulla qui irure aute sunt ullamco esse sit. Est ipsum eu officia Lorem enim adipisicing officia est laboris. Exercitation ipsum excepteur ut enim aliquip incididunt ut consectetur.\r\n',
    registered: '2016-12-27T10:06:18 -03:00',
    latitude: 18.188012,
    longitude: 71.477966,
    tags: [
      'culpa',
      'duis',
      'labore',
      'fugiat',
      'sunt',
      'dolore',
      'deserunt',
    ],
    friends: [
      {
        id: 0,
        name: 'Gill Porter',
      },
      {
        id: 1,
        name: 'Nadine Sanford',
      },
      {
        id: 2,
        name: 'Janine Mason',
      },
    ],
    greeting: 'Hello, Slater Marsh! You have 5 unread messages.',
    favoriteFruit: 'banana',
  },
];

export default data;
